// Autor: Manuel Schmocker
// Datum: 17.09.2022
package ch.manuel.igctoraster.gui;

import ch.manuel.igctoraster.DataHandler;
import ch.manuel.utilities.MyUtilities;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Schmocker
 */
public class MainFrame extends javax.swing.JFrame {

  public static InfoForm infoForm;
  private static DataHandler dHandler;
  private static Point ptClicked;
  private static Point ptDragged;
  // icon in resources
  private static final String icon = "/data/icon.png";
  
  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();
    setIcon();
    initFrames();

    ptClicked = null;
  }

  /**
   * Creates the depending frames
   */
  private void initFrames() {
    // create InfoFrame, don't show it
    java.awt.EventQueue.invokeLater(() -> {
      infoForm = new InfoForm(new javax.swing.JFrame(), true);
      infoForm.setVisible(false);
    });
  }
  
  // set icon
  private void setIcon() {
    Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource(icon));
    this.setIconImage(image);
  }

  // class methodes
  public static void setStatusText(String str) {
    MainFrame.jTextField1.setText(str);
  }

  public static void updateGraphicPanel() {
    MainFrame.graphicPanel1.repaintPanel();
  }

  public static void setMenuSaveActive() {
    MainFrame.jMenuItem3.setEnabled(true);
    MainFrame.jMenuItem6.setEnabled(true);
  }
  
  public static int getCellsizeFromInput() {
    return (int) jSpinner1.getModel().getValue();
  } 
  
  

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    graphicPanel1 = new ch.manuel.igctoraster.graphics.GraphicPanel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("IGC Analyzer");

    graphicPanel1.setBackground(new java.awt.Color(204, 204, 204));
    graphicPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        graphicPanel1MouseDragged(evt);
      }
    });
    graphicPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
      public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
        graphicPanel1MouseWheelMoved(evt);
      }
    });
    graphicPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        graphicPanel1MouseClicked(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        graphicPanel1MouseReleased(evt);
      }
    });

    javax.swing.GroupLayout graphicPanel1Layout = new javax.swing.GroupLayout(graphicPanel1);
    graphicPanel1.setLayout(graphicPanel1Layout);
    graphicPanel1Layout.setHorizontalGroup(
      graphicPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 800, Short.MAX_VALUE)
    );
    graphicPanel1Layout.setVerticalGroup(
      graphicPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 541, Short.MAX_VALUE)
    );

    jTextField1.setEditable(false);
    jTextField1.setBackground(new java.awt.Color(255, 255, 255));
    jTextField1.setForeground(new java.awt.Color(102, 102, 102));
    jTextField1.setText("Status: No info");
    jTextField1.setBorder(null);
    jTextField1.setPreferredSize(new java.awt.Dimension(300, 15));

    jLabel1.setText("Cellsize");

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(500, 50, 10000, 1));
    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSpinner1StateChanged(evt);
      }
    });

    jMenu1.setText("File");

    jMenuItem2.setText("Open IGC");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem5.setText("Open IGC (multiple)");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem5ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem5);

    jMenuItem7.setText("Exit");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem7ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem7);

    jMenuBar1.add(jMenu1);

    jMenu4.setText("Export");

    jMenuItem3.setText("Save xyz file");
    jMenuItem3.setEnabled(false);
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu4.add(jMenuItem3);

    jMenuItem6.setText("Save PNG (.png)");
    jMenuItem6.setActionCommand("Save PNG");
    jMenuItem6.setEnabled(false);
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem6ActionPerformed(evt);
      }
    });
    jMenu4.add(jMenuItem6);

    jMenuBar1.add(jMenu4);

    jMenu3.setText("View");

    jMenuItem4.setText("Reset view");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu2.setText("Info");

    jMenuItem1.setText("About");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem1);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(graphicPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(graphicPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // show InfoForm
    infoForm.setVisible(true);
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void graphicPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphicPanel1MouseClicked
    // click on panel
    Point p = new Point(evt.getX(), evt.getY());
    MainFrame.graphicPanel1.setNameOnClick(p);
    MainFrame.graphicPanel1.repaintPanel();
  }//GEN-LAST:event_graphicPanel1MouseClicked

  private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    // open file dialog
    File file;
    FileFilter filter = new FileNameExtensionFilter("IGC files", "igc");
    file = MyUtilities.getOpenFileDialog("Open IGC-File", filter);
    if (file != null) {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "Load file: " + file.getName());
      dHandler = new DataHandler(file);
      dHandler.processSingleFile();
    } else {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "No file...");
    }
  }//GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    // open save dialog: as text file, xyz file
    File file;
    FileFilter filter = new FileNameExtensionFilter("xyz file", "tiff");
    file = MyUtilities.getSaveFileDialog("Save as text file", filter, "xyz.txt");
    dHandler.saveXYZ(file);
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void graphicPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_graphicPanel1MouseWheelMoved
    // zoom
    Point p = new Point(evt.getX(), evt.getY());
    if (evt.getWheelRotation() < 0) {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "zoom in" + p.toString());
      MainFrame.graphicPanel1.zoomIn(p);
    } else if (evt.getWheelRotation() > 0) {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "zoom out" + p.toString());
      MainFrame.graphicPanel1.zoomOut(p);
    }
  }//GEN-LAST:event_graphicPanel1MouseWheelMoved

  private void graphicPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphicPanel1MouseDragged
    // get vector for drag map
    if (ptClicked == null) {
      ptClicked = new Point(evt.getX(), evt.getY());
    }
    ptDragged = new Point(evt.getX() - (int) ptClicked.getX(), evt.getY() - (int) ptClicked.getY());
  }//GEN-LAST:event_graphicPanel1MouseDragged

  private void graphicPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphicPanel1MouseReleased
    // drag map
    MainFrame.graphicPanel1.dragMap(ptDragged);
    ptClicked = null;
  }//GEN-LAST:event_graphicPanel1MouseReleased

  private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    MainFrame.graphicPanel1.resetView();
  }//GEN-LAST:event_jMenuItem4ActionPerformed

  private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    // open file dialog
    File file;
    file = MyUtilities.getSelectFolderDialog("Select folder");
    if (file != null) {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "Open folder: " + file.getName());
      dHandler = new DataHandler(file);
      dHandler.processFiles();
    } else {
      Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "No file...");
    }
  }//GEN-LAST:event_jMenuItem5ActionPerformed

  private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    // exit application
    System.exit(0);
  }//GEN-LAST:event_jMenuItem7ActionPerformed

  private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    // open save dialog: PNG file
    File file;
    FileFilter filter = new FileNameExtensionFilter("PNG files", "png");
    file = MyUtilities.getSaveFileDialog("Save PNG", filter, "image.png");
    dHandler.saveImage(file);
  }//GEN-LAST:event_jMenuItem6ActionPerformed

  private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
    MainFrame.setStatusText("Cellsize change to " + jSpinner1.getModel().getValue().toString() + " m");
  }//GEN-LAST:event_jSpinner1StateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private static ch.manuel.igctoraster.graphics.GraphicPanel graphicPanel1;
  private static javax.swing.JLabel jLabel1;
  private static javax.swing.JMenu jMenu1;
  private static javax.swing.JMenu jMenu2;
  private static javax.swing.JMenu jMenu3;
  private static javax.swing.JMenu jMenu4;
  private static javax.swing.JMenuBar jMenuBar1;
  private static javax.swing.JMenuItem jMenuItem1;
  private static javax.swing.JMenuItem jMenuItem2;
  private static javax.swing.JMenuItem jMenuItem3;
  private static javax.swing.JMenuItem jMenuItem4;
  private static javax.swing.JMenuItem jMenuItem5;
  private static javax.swing.JMenuItem jMenuItem6;
  private static javax.swing.JMenuItem jMenuItem7;
  private static javax.swing.JSpinner jSpinner1;
  private static javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
